services:
  inv-1:
    build:
      context: .
      dockerfile: ./apps/inventory-1/Dockerfile
      target: development
    command: npm run start:dev inventory-1
    env_file:
      - ./.env
    depends_on:
      - db-1
      - rabbitmq
    ports:
      - '3000:3000'
  inv-2:
    build:
      context: .
      dockerfile: ./apps/inventory-2/Dockerfile
      target: development
    command: npm run start:dev inventory-2
    env_file:
      - ./.env
    depends_on:
      - db-2
      - rabbitmq
    ports:
      - '3001:3001'
  db-1:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6675:5432'
    volumes: 
      - db-1:/var/lib/postgresql/data
  db-2:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6676:5432'
    volumes: 
      - db-2:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672
volumes:
  db-1:
    driver: local
  db-2:
    driver: local